# Generated by Django 3.2.2 on 2021-05-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='branding',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='marketing',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
